version: '3.2'
services:
  web:
    image: odoo_salam:v1
    ports:
      - '8069:8069'
      - '8072:8072'
    environment:
      - HOST=10.116.70.141
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5432
    volumes:
      - /data/Odoo:/var/lib/odoo
      - /etc/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: >
      /bin/bash -c "odoo -u all --stop-after-init && odoo"

volumes:
  odoo-web-data:




